version: "2"

run:
  timeout: 15m
  go: '1.26.6'

linters:
  default: none
  settings:
    staticcheck:
      checks: [ "all", "-ST1001" ]  # Disables dot-import warnings
    revive:
      rules:
        - name: dot-imports
          disabled: true
    gosec:
      excludes:
        - G404 #Use of weak random number generator (math/rand or math/rand/v2). It is only used in tests.
  enable:
    - decorder
    - errcheck
    - errorlint
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports
