apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: {{ .Values.namespace }}
data:
  fluentd.conf: |
    <source>
        @type tail
        # Matching the following log files:
        #   fleet-hub-agent-*_fleet-hub-agent-*.log
        #   fleet-member-agent-*_msi-adapter-*.log
        #   fleet-member-agent-*_refresh-tokent-*.log
        #   fleet-member-agent-*_fleet-member-agent-*.log
        path /var/log/containers/fleet-*-agent-*.log
        path_key tailed_path
        pos_file /var/log/td-agent.fleet-agent.log.pos
        tag arc-extension.fleet-agent.*
        read_from_head true
        <parse>
            @type regexp
            time_format %Y-%m-%dT%H:%M:%S.%L%z
            expression /^(?<time>.+)\s*(?<stream>stdout|stderr)\s*(?<partitiontag>[PF])\s*(?<log>.*)$/
        </parse>
    </source>
    # Collect logs for fleet networking controller managers
    <source>
        @type tail
        path /var/log/containers/fleet-*-controller-manager-*.log
        path_key tailed_path
        pos_file /var/log/td-agent.fleet-net-controller-manager.log.pos
        tag arc-extension.fleet-agent.*
        read_from_head true
        <parse>
            @type regexp
            time_format %Y-%m-%dT%H:%M:%S.%L%z
            expression /^(?<time>.+)\s*(?<stream>stdout|stderr)\s*(?<partitiontag>[PF])\s*(?<log>.*)$/
        </parse>
    </source>
    # Add tag arc.fleetagent to logs from fleet agents
    <match arc-extension.fleet-agent.**>
        @type rewrite_tag_filter
        <rule>
            key namespace
            pattern ^.*$
            tag arc.fleetagent
        </rule>
    </match>
