apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-07-27T20:01:31.145180808Z"
    description: A Helm chart for Kubernetes
    digest: 086ac607be3411baf60ebb8df5094e66b836094f5e5e4fe42eee89fc9d82e741
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-07-27T20:01:31.146465691Z"
    description: A Helm chart for hub agent
    digest: 10edadaabbecc85e29ba0c50ab00ca3caa1a8ee7b069990251e2a8b86031b3a9
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-07-27T20:01:31.146993828Z"
    description: Helm chart for member agent.
    digest: 87e7bac771908d51782a527715e7135b28a41db07daeb092d88fc95012f7ac89
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2026-07-27T20:01:31.144029011Z"
