apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-07-27T16:03:45.167888293Z"
    description: A Helm chart for Kubernetes
    digest: b04a57867089cf34ad5505e88ad835a427571a5260cc2623029cc4bb5aad9742
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-07-27T16:03:45.169019207Z"
    description: A Helm chart for hub agent
    digest: 09348e1911162128b203b436f90d1845791316a7302766d396113bf08eda825f
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-07-27T16:03:45.169547364Z"
    description: Helm chart for member agent.
    digest: 256bd1ceade3b06913002eaa2da73b64c04d5cbccc9f5946c4af12e10189f473
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2026-07-27T16:03:45.167329901Z"
