apiVersion: v1
entries:
  arc-member-cluster-agents-helm-chart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-08-19T22:26:37.028584115Z"
    description: A Helm chart for Kubernetes
    digest: f794bc96e48cee7bd26622c4083b60f7094e4d5d86281c50fbd5d6af2fc0bdcc
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-06-22T18:55:46.007052448Z"
    description: A Helm chart for Kubernetes
    digest: 7f81782b611d1715b833127ae8a6f80af5b2b9e8143b7d349725363f03350487
    name: arc-member-cluster-agents-helm-chart
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/arc-member-cluster-agents-helm-chart-0.0.0.tgz
    version: 0.0.0
  hub-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-06-22T18:55:46.008221701Z"
    description: A Helm chart for hub agent
    digest: 39f80ad8197ed29a26b45e0e6685387581b8e2cbe1278b396e6766b4e7e03ced
    name: hub-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/hub-agent-0.1.0.tgz
    version: 0.1.0
  member-agent:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-06-22T18:55:46.008707844Z"
    description: Helm chart for member agent.
    digest: 7ab3a1dc7a2bd02b735582f3a30eb2287f331d4e2b0f62c057bcb48afb25637d
    name: member-agent
    type: application
    urls:
    - https://Azure.github.io/fleet/charts/member-agent-0.1.0.tgz
    version: 0.1.0
generated: "2026-06-22T18:55:46.006498874Z"
