//go:build !ignore_autogenerated

/*
Copyright (c) Microsoft Corporation.
Licensed under the MIT license.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetResourceSelector) DeepCopyInto(out *FleetResourceSelector) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetResourceSelector.
func (in *FleetResourceSelector) DeepCopy() *FleetResourceSelector {
	if in == nil {
		return nil
	}
	out := new(FleetResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationAttempt) DeepCopyInto(out *NotificationAttempt) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationAttempt.
func (in *NotificationAttempt) DeepCopy() *NotificationAttempt {
	if in == nil {
		return nil
	}
	out := new(NotificationAttempt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationAttempt) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationAttemptList) DeepCopyInto(out *NotificationAttemptList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotificationAttempt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationAttemptList.
func (in *NotificationAttemptList) DeepCopy() *NotificationAttemptList {
	if in == nil {
		return nil
	}
	out := new(NotificationAttemptList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationAttemptList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationAttemptSpec) DeepCopyInto(out *NotificationAttemptSpec) {
	*out = *in
	out.Regarding = in.Regarding
	out.Message = in.Message
	out.NotificationProviderClass = in.NotificationProviderClass
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationAttemptSpec.
func (in *NotificationAttemptSpec) DeepCopy() *NotificationAttemptSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationAttemptSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationAttemptStatus) DeepCopyInto(out *NotificationAttemptStatus) {
	*out = *in
	if in.FailedAttempts != nil {
		in, out := &in.FailedAttempts, &out.FailedAttempts
		*out = new(int32)
		**out = **in
	}
	if in.LastAttemptedTimestamp != nil {
		in, out := &in.LastAttemptedTimestamp, &out.LastAttemptedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationAttemptStatus.
func (in *NotificationAttemptStatus) DeepCopy() *NotificationAttemptStatus {
	if in == nil {
		return nil
	}
	out := new(NotificationAttemptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfig) DeepCopyInto(out *NotificationConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfig.
func (in *NotificationConfig) DeepCopy() *NotificationConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfigList) DeepCopyInto(out *NotificationConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotificationConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfigList.
func (in *NotificationConfigList) DeepCopy() *NotificationConfigList {
	if in == nil {
		return nil
	}
	out := new(NotificationConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfigSpec) DeepCopyInto(out *NotificationConfigSpec) {
	*out = *in
	in.TargetSelector.DeepCopyInto(&out.TargetSelector)
	if in.OnceEveryMinutes != nil {
		in, out := &in.OnceEveryMinutes, &out.OnceEveryMinutes
		*out = new(int32)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(int32)
		**out = **in
	}
	if in.TriggerThreshold != nil {
		in, out := &in.TriggerThreshold, &out.TriggerThreshold
		*out = new(int32)
		**out = **in
	}
	if in.NotificationMessageTemplate != nil {
		in, out := &in.NotificationMessageTemplate, &out.NotificationMessageTemplate
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.NotificationProviderClass != nil {
		in, out := &in.NotificationProviderClass, &out.NotificationProviderClass
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.NotificationAttemptHistoryLimit != nil {
		in, out := &in.NotificationAttemptHistoryLimit, &out.NotificationAttemptHistoryLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfigSpec.
func (in *NotificationConfigSpec) DeepCopy() *NotificationConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfigStatus) DeepCopyInto(out *NotificationConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfigStatus.
func (in *NotificationConfigStatus) DeepCopy() *NotificationConfigStatus {
	if in == nil {
		return nil
	}
	out := new(NotificationConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationProviderClass) DeepCopyInto(out *NotificationProviderClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationProviderClass.
func (in *NotificationProviderClass) DeepCopy() *NotificationProviderClass {
	if in == nil {
		return nil
	}
	out := new(NotificationProviderClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationProviderClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationProviderClassList) DeepCopyInto(out *NotificationProviderClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotificationProviderClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationProviderClassList.
func (in *NotificationProviderClassList) DeepCopy() *NotificationProviderClassList {
	if in == nil {
		return nil
	}
	out := new(NotificationProviderClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationProviderClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationProviderClassSpec) DeepCopyInto(out *NotificationProviderClassSpec) {
	*out = *in
	out.Parameters = in.Parameters
	if in.MaxDeliveryAttempts != nil {
		in, out := &in.MaxDeliveryAttempts, &out.MaxDeliveryAttempts
		*out = new(int32)
		**out = **in
	}
	if in.StaleAfterMinutes != nil {
		in, out := &in.StaleAfterMinutes, &out.StaleAfterMinutes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationProviderClassSpec.
func (in *NotificationProviderClassSpec) DeepCopy() *NotificationProviderClassSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationProviderClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationProviderClassStatus) DeepCopyInto(out *NotificationProviderClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationProviderClassStatus.
func (in *NotificationProviderClassStatus) DeepCopy() *NotificationProviderClassStatus {
	if in == nil {
		return nil
	}
	out := new(NotificationProviderClassStatus)
	in.DeepCopyInto(out)
	return out
}
