memberagent:
  repository: mcr.microsoft.com/aks/fleet/member-agent
  tag: "${MEMBER_AGENT_IMAGE_VERSION}"

mcscontrollermanager:
  repository: mcr.microsoft.com/aks/fleet/mcs-controller-manager
  tag: "${MCS_CONTROLLER_IMAGE_VERSION}"

membernetcontrollermanager:
  repository: mcr.microsoft.com/aks/fleet/member-net-controller-manager
  tag: "${MEMBER_NET_CONTROLLER_IMAGE_VERSION}"

refreshtoken:
  repository: mcr.microsoft.com/aks/fleet/refresh-token
  tag: "${REFRESH_TOKEN_IMAGE_VERSION}"

crdinstaller:
  enabled: true
  repository: mcr.microsoft.com/aks/fleet/crd-installer
  tag: "${CRD_INSTALLER_IMAGE_VERSION}"
  logVerbosity: 2

logVerbosity: 5

namespace: fleet-system

config:
  scope: ""
  hubURL : ""
  memberClusterName: ""
  hubCA: ""

enableTrafficManagerFeature: false
enableNetworkingFeatures: false

geneva:
  mdsd:
    repository: linuxgeneva-microsoft.azurecr.io/genevamdsd
    tag: "${GENEVA_MDSD_IMAGE_VERSION}"
  fluentd:
    repository: linuxgeneva-microsoft.azurecr.io/genevafluentd_td-agent
    tag: "${GENEVA_FLUENTD_IMAGE_VERSION}"
  mdm:
    repository: linuxgeneva-microsoft.azurecr.io/genevamdm
    tag: "${GENEVA_MDM_IMAGE_VERSION}"
    account: ""
  gcs:
    environment: ""
    account: ""
    region: ""
    namespace: ""
    configVersion: ""
    authIdType: "AuthMSIToken"
  config:
    tenant: ""
    role: ""
    azureEnvironment: ""
    enableGigBridgeMode: "1"
  debugging:
    dockerLogging: "false"

Azure:
  proxySettings:
    isProxyEnabled: "false"
    httpProxy: ""
    httpsProxy: ""
    noProxy: ""
    proxyCert: ""