//
//Copyright 2025 The KubeFleet Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: apis/protos/azure/compute/v1/vmsizerecommender.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttributeBasedVMSizeRecommenderService_GenerateAttributeBasedRecommendations_FullMethodName = "/azure.compute.v1.AttributeBasedVMSizeRecommenderService/GenerateAttributeBasedRecommendations"
)

// AttributeBasedVMSizeRecommenderServiceClient is the client API for AttributeBasedVMSizeRecommenderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for generating attribute-based VM size recommendations
type AttributeBasedVMSizeRecommenderServiceClient interface {
	// Generate VM size recommendations based on specified attributes and requirements.
	GenerateAttributeBasedRecommendations(ctx context.Context, in *GenerateAttributeBasedRecommendationsRequest, opts ...grpc.CallOption) (*GenerateAttributeBasedRecommendationsResponse, error)
}

type attributeBasedVMSizeRecommenderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttributeBasedVMSizeRecommenderServiceClient(cc grpc.ClientConnInterface) AttributeBasedVMSizeRecommenderServiceClient {
	return &attributeBasedVMSizeRecommenderServiceClient{cc}
}

func (c *attributeBasedVMSizeRecommenderServiceClient) GenerateAttributeBasedRecommendations(ctx context.Context, in *GenerateAttributeBasedRecommendationsRequest, opts ...grpc.CallOption) (*GenerateAttributeBasedRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAttributeBasedRecommendationsResponse)
	err := c.cc.Invoke(ctx, AttributeBasedVMSizeRecommenderService_GenerateAttributeBasedRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttributeBasedVMSizeRecommenderServiceServer is the server API for AttributeBasedVMSizeRecommenderService service.
// All implementations must embed UnimplementedAttributeBasedVMSizeRecommenderServiceServer
// for forward compatibility.
//
// Service for generating attribute-based VM size recommendations
type AttributeBasedVMSizeRecommenderServiceServer interface {
	// Generate VM size recommendations based on specified attributes and requirements.
	GenerateAttributeBasedRecommendations(context.Context, *GenerateAttributeBasedRecommendationsRequest) (*GenerateAttributeBasedRecommendationsResponse, error)
	mustEmbedUnimplementedAttributeBasedVMSizeRecommenderServiceServer()
}

// UnimplementedAttributeBasedVMSizeRecommenderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttributeBasedVMSizeRecommenderServiceServer struct{}

func (UnimplementedAttributeBasedVMSizeRecommenderServiceServer) GenerateAttributeBasedRecommendations(context.Context, *GenerateAttributeBasedRecommendationsRequest) (*GenerateAttributeBasedRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAttributeBasedRecommendations not implemented")
}
func (UnimplementedAttributeBasedVMSizeRecommenderServiceServer) mustEmbedUnimplementedAttributeBasedVMSizeRecommenderServiceServer() {
}
func (UnimplementedAttributeBasedVMSizeRecommenderServiceServer) testEmbeddedByValue() {}

// UnsafeAttributeBasedVMSizeRecommenderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttributeBasedVMSizeRecommenderServiceServer will
// result in compilation errors.
type UnsafeAttributeBasedVMSizeRecommenderServiceServer interface {
	mustEmbedUnimplementedAttributeBasedVMSizeRecommenderServiceServer()
}

func RegisterAttributeBasedVMSizeRecommenderServiceServer(s grpc.ServiceRegistrar, srv AttributeBasedVMSizeRecommenderServiceServer) {
	// If the following call pancis, it indicates UnimplementedAttributeBasedVMSizeRecommenderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttributeBasedVMSizeRecommenderService_ServiceDesc, srv)
}

func _AttributeBasedVMSizeRecommenderService_GenerateAttributeBasedRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAttributeBasedRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttributeBasedVMSizeRecommenderServiceServer).GenerateAttributeBasedRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttributeBasedVMSizeRecommenderService_GenerateAttributeBasedRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttributeBasedVMSizeRecommenderServiceServer).GenerateAttributeBasedRecommendations(ctx, req.(*GenerateAttributeBasedRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttributeBasedVMSizeRecommenderService_ServiceDesc is the grpc.ServiceDesc for AttributeBasedVMSizeRecommenderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttributeBasedVMSizeRecommenderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "azure.compute.v1.AttributeBasedVMSizeRecommenderService",
	HandlerType: (*AttributeBasedVMSizeRecommenderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAttributeBasedRecommendations",
			Handler:    _AttributeBasedVMSizeRecommenderService_GenerateAttributeBasedRecommendations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis/protos/azure/compute/v1/vmsizerecommender.proto",
}
