//
//Copyright 2025 The KubeFleet Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.0
// source: apis/protos/azure/compute/v1/vmsizerecommender.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Capacity unit types
type CapacityUnitType int32

const (
	CapacityUnitType_CAPACITY_UNIT_TYPE_UNSPECIFIED       CapacityUnitType = 0
	CapacityUnitType_CAPACITY_UNIT_TYPE_VM_INSTANCE_COUNT CapacityUnitType = 1
)

// Enum value maps for CapacityUnitType.
var (
	CapacityUnitType_name = map[int32]string{
		0: "CAPACITY_UNIT_TYPE_UNSPECIFIED",
		1: "CAPACITY_UNIT_TYPE_VM_INSTANCE_COUNT",
	}
	CapacityUnitType_value = map[string]int32{
		"CAPACITY_UNIT_TYPE_UNSPECIFIED":       0,
		"CAPACITY_UNIT_TYPE_VM_INSTANCE_COUNT": 1,
	}
)

func (x CapacityUnitType) Enum() *CapacityUnitType {
	p := new(CapacityUnitType)
	*p = x
	return p
}

func (x CapacityUnitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapacityUnitType) Descriptor() protoreflect.EnumDescriptor {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_enumTypes[0].Descriptor()
}

func (CapacityUnitType) Type() protoreflect.EnumType {
	return &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_enumTypes[0]
}

func (x CapacityUnitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapacityUnitType.Descriptor instead.
func (CapacityUnitType) EnumDescriptor() ([]byte, []int) {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP(), []int{0}
}

// Restrictions filter
type RecommendationProperties_RestrictionsFilter int32

const (
	RecommendationProperties_RESTRICTIONS_FILTER_UNSPECIFIED                  RecommendationProperties_RestrictionsFilter = 0
	RecommendationProperties_RESTRICTIONS_FILTER_NONE                         RecommendationProperties_RestrictionsFilter = 1
	RecommendationProperties_RESTRICTIONS_FILTER_OFFER_RESTRICTIONS           RecommendationProperties_RestrictionsFilter = 2
	RecommendationProperties_RESTRICTIONS_FILTER_QUOTA_RESTRICTIONS           RecommendationProperties_RestrictionsFilter = 3
	RecommendationProperties_RESTRICTIONS_FILTER_QUOTA_AND_OFFER_RESTRICTIONS RecommendationProperties_RestrictionsFilter = 4
)

// Enum value maps for RecommendationProperties_RestrictionsFilter.
var (
	RecommendationProperties_RestrictionsFilter_name = map[int32]string{
		0: "RESTRICTIONS_FILTER_UNSPECIFIED",
		1: "RESTRICTIONS_FILTER_NONE",
		2: "RESTRICTIONS_FILTER_OFFER_RESTRICTIONS",
		3: "RESTRICTIONS_FILTER_QUOTA_RESTRICTIONS",
		4: "RESTRICTIONS_FILTER_QUOTA_AND_OFFER_RESTRICTIONS",
	}
	RecommendationProperties_RestrictionsFilter_value = map[string]int32{
		"RESTRICTIONS_FILTER_UNSPECIFIED":                  0,
		"RESTRICTIONS_FILTER_NONE":                         1,
		"RESTRICTIONS_FILTER_OFFER_RESTRICTIONS":           2,
		"RESTRICTIONS_FILTER_QUOTA_RESTRICTIONS":           3,
		"RESTRICTIONS_FILTER_QUOTA_AND_OFFER_RESTRICTIONS": 4,
	}
)

func (x RecommendationProperties_RestrictionsFilter) Enum() *RecommendationProperties_RestrictionsFilter {
	p := new(RecommendationProperties_RestrictionsFilter)
	*p = x
	return p
}

func (x RecommendationProperties_RestrictionsFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommendationProperties_RestrictionsFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_enumTypes[1].Descriptor()
}

func (RecommendationProperties_RestrictionsFilter) Type() protoreflect.EnumType {
	return &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_enumTypes[1]
}

func (x RecommendationProperties_RestrictionsFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommendationProperties_RestrictionsFilter.Descriptor instead.
func (RecommendationProperties_RestrictionsFilter) EnumDescriptor() ([]byte, []int) {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP(), []int{4, 0}
}

// VM attributes specification
type VMAttributes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// optional
	// List of Azure Vm Sizes only to filter based on above attributes provided
	AllowedVmSizes []string `protobuf:"bytes,1,rep,name=allowed_vm_sizes,json=allowedVmSizes,proto3" json:"allowed_vm_sizes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VMAttributes) Reset() {
	*x = VMAttributes{}
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMAttributes) ProtoMessage() {}

func (x *VMAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMAttributes.ProtoReflect.Descriptor instead.
func (*VMAttributes) Descriptor() ([]byte, []int) {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP(), []int{0}
}

func (x *VMAttributes) GetAllowedVmSizes() []string {
	if x != nil {
		return x.AllowedVmSizes
	}
	return nil
}

// Resource properties
type ResourceProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// optional
	// Object contains specific requirements for Vm sizes attributes to filter.
	VmAttributes  *VMAttributes `protobuf:"bytes,1,opt,name=vm_attributes,json=vmAttributes,proto3" json:"vm_attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceProperties) Reset() {
	*x = ResourceProperties{}
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceProperties) ProtoMessage() {}

func (x *ResourceProperties) ProtoReflect() protoreflect.Message {
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceProperties.ProtoReflect.Descriptor instead.
func (*ResourceProperties) Descriptor() ([]byte, []int) {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceProperties) GetVmAttributes() *VMAttributes {
	if x != nil {
		return x.VmAttributes
	}
	return nil
}

// Priority profile for regular VMs
type RegularPriorityProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// optional
	CapacityUnitType CapacityUnitType `protobuf:"varint,1,opt,name=capacity_unit_type,json=capacityUnitType,proto3,enum=azure.compute.v1.CapacityUnitType" json:"capacity_unit_type,omitempty"`
	// optional
	// Expected values: >0
	TargetCapacity uint32 `protobuf:"varint,2,opt,name=target_capacity,json=targetCapacity,proto3" json:"target_capacity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegularPriorityProfile) Reset() {
	*x = RegularPriorityProfile{}
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegularPriorityProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegularPriorityProfile) ProtoMessage() {}

func (x *RegularPriorityProfile) ProtoReflect() protoreflect.Message {
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegularPriorityProfile.ProtoReflect.Descriptor instead.
func (*RegularPriorityProfile) Descriptor() ([]byte, []int) {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP(), []int{2}
}

func (x *RegularPriorityProfile) GetCapacityUnitType() CapacityUnitType {
	if x != nil {
		return x.CapacityUnitType
	}
	return CapacityUnitType_CAPACITY_UNIT_TYPE_UNSPECIFIED
}

func (x *RegularPriorityProfile) GetTargetCapacity() uint32 {
	if x != nil {
		return x.TargetCapacity
	}
	return 0
}

// Priority profile for spot VMs
type SpotPriorityProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// optional
	CapacityUnitType CapacityUnitType `protobuf:"varint,1,opt,name=capacity_unit_type,json=capacityUnitType,proto3,enum=azure.compute.v1.CapacityUnitType" json:"capacity_unit_type,omitempty"`
	// optional
	// Note: SDK is using float32 while internal doc is using double.
	// maxPricePerVM for spot instance in USD
	MaxPricePerVm float32 `protobuf:"fixed32,2,opt,name=max_price_per_vm,json=maxPricePerVm,proto3" json:"max_price_per_vm,omitempty"`
	// optional
	// Expected values: >0
	TargetCapacity uint32 `protobuf:"varint,3,opt,name=target_capacity,json=targetCapacity,proto3" json:"target_capacity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpotPriorityProfile) Reset() {
	*x = SpotPriorityProfile{}
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpotPriorityProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotPriorityProfile) ProtoMessage() {}

func (x *SpotPriorityProfile) ProtoReflect() protoreflect.Message {
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotPriorityProfile.ProtoReflect.Descriptor instead.
func (*SpotPriorityProfile) Descriptor() ([]byte, []int) {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP(), []int{3}
}

func (x *SpotPriorityProfile) GetCapacityUnitType() CapacityUnitType {
	if x != nil {
		return x.CapacityUnitType
	}
	return CapacityUnitType_CAPACITY_UNIT_TYPE_UNSPECIFIED
}

func (x *SpotPriorityProfile) GetMaxPricePerVm() float32 {
	if x != nil {
		return x.MaxPricePerVm
	}
	return 0
}

func (x *SpotPriorityProfile) GetTargetCapacity() uint32 {
	if x != nil {
		return x.TargetCapacity
	}
	return 0
}

// Recommendation properties
type RecommendationProperties struct {
	state              protoimpl.MessageState                      `protogen:"open.v1"`
	RestrictionsFilter RecommendationProperties_RestrictionsFilter `protobuf:"varint,1,opt,name=restrictions_filter,json=restrictionsFilter,proto3,enum=azure.compute.v1.RecommendationProperties_RestrictionsFilter" json:"restrictions_filter,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecommendationProperties) Reset() {
	*x = RecommendationProperties{}
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationProperties) ProtoMessage() {}

func (x *RecommendationProperties) ProtoReflect() protoreflect.Message {
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationProperties.ProtoReflect.Descriptor instead.
func (*RecommendationProperties) Descriptor() ([]byte, []int) {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP(), []int{4}
}

func (x *RecommendationProperties) GetRestrictionsFilter() RecommendationProperties_RestrictionsFilter {
	if x != nil {
		return x.RestrictionsFilter
	}
	return RecommendationProperties_RESTRICTIONS_FILTER_UNSPECIFIED
}

// Properties of a recommended VM size
// Note: it only exposes whatever fields we need for now.
type RecommendedVMSizeProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Family of the VM size
	Family string `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	// Name of the VM size
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Size of the VM
	Size          string `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendedVMSizeProperties) Reset() {
	*x = RecommendedVMSizeProperties{}
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedVMSizeProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedVMSizeProperties) ProtoMessage() {}

func (x *RecommendedVMSizeProperties) ProtoReflect() protoreflect.Message {
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedVMSizeProperties.ProtoReflect.Descriptor instead.
func (*RecommendedVMSizeProperties) Descriptor() ([]byte, []int) {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP(), []int{5}
}

func (x *RecommendedVMSizeProperties) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *RecommendedVMSizeProperties) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecommendedVMSizeProperties) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

// Collection of recommended VM sizes
type RecommendedVMSizes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of recommended regular VM sizes
	RegularVmSizes []*RecommendedVMSizeProperties `protobuf:"bytes,1,rep,name=regular_vm_sizes,json=regularVmSizes,proto3" json:"regular_vm_sizes,omitempty"`
	// List of recommended spot VM sizes
	SpotVmSizes   []*RecommendedVMSizeProperties `protobuf:"bytes,2,rep,name=spot_vm_sizes,json=spotVmSizes,proto3" json:"spot_vm_sizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendedVMSizes) Reset() {
	*x = RecommendedVMSizes{}
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedVMSizes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedVMSizes) ProtoMessage() {}

func (x *RecommendedVMSizes) ProtoReflect() protoreflect.Message {
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedVMSizes.ProtoReflect.Descriptor instead.
func (*RecommendedVMSizes) Descriptor() ([]byte, []int) {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP(), []int{6}
}

func (x *RecommendedVMSizes) GetRegularVmSizes() []*RecommendedVMSizeProperties {
	if x != nil {
		return x.RegularVmSizes
	}
	return nil
}

func (x *RecommendedVMSizes) GetSpotVmSizes() []*RecommendedVMSizeProperties {
	if x != nil {
		return x.SpotVmSizes
	}
	return nil
}

// Request to generate attribute-based VM size recommendations
type GenerateAttributeBasedRecommendationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subscription_id - target managed cluster subscription id
	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// location - target managed cluster location
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	// One of the regularPriorityProfile or spotPriorityProfile must be provided.
	//
	// Types that are valid to be assigned to PriorityProfile:
	//
	//	*GenerateAttributeBasedRecommendationsRequest_RegularPriorityProfile
	//	*GenerateAttributeBasedRecommendationsRequest_SpotPriorityProfile
	PriorityProfile isGenerateAttributeBasedRecommendationsRequest_PriorityProfile `protobuf_oneof:"priority_profile"`
	// optional
	// Object of different recommendationProperties
	RecommendationProperties *RecommendationProperties `protobuf:"bytes,5,opt,name=recommendation_properties,json=recommendationProperties,proto3" json:"recommendation_properties,omitempty"`
	// Object of resourceProperties
	// Note: it only exposes whatever fields are required for now.
	ResourceProperties *ResourceProperties `protobuf:"bytes,6,opt,name=resource_properties,json=resourceProperties,proto3" json:"resource_properties,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GenerateAttributeBasedRecommendationsRequest) Reset() {
	*x = GenerateAttributeBasedRecommendationsRequest{}
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAttributeBasedRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAttributeBasedRecommendationsRequest) ProtoMessage() {}

func (x *GenerateAttributeBasedRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAttributeBasedRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GenerateAttributeBasedRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateAttributeBasedRecommendationsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *GenerateAttributeBasedRecommendationsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GenerateAttributeBasedRecommendationsRequest) GetPriorityProfile() isGenerateAttributeBasedRecommendationsRequest_PriorityProfile {
	if x != nil {
		return x.PriorityProfile
	}
	return nil
}

func (x *GenerateAttributeBasedRecommendationsRequest) GetRegularPriorityProfile() *RegularPriorityProfile {
	if x != nil {
		if x, ok := x.PriorityProfile.(*GenerateAttributeBasedRecommendationsRequest_RegularPriorityProfile); ok {
			return x.RegularPriorityProfile
		}
	}
	return nil
}

func (x *GenerateAttributeBasedRecommendationsRequest) GetSpotPriorityProfile() *SpotPriorityProfile {
	if x != nil {
		if x, ok := x.PriorityProfile.(*GenerateAttributeBasedRecommendationsRequest_SpotPriorityProfile); ok {
			return x.SpotPriorityProfile
		}
	}
	return nil
}

func (x *GenerateAttributeBasedRecommendationsRequest) GetRecommendationProperties() *RecommendationProperties {
	if x != nil {
		return x.RecommendationProperties
	}
	return nil
}

func (x *GenerateAttributeBasedRecommendationsRequest) GetResourceProperties() *ResourceProperties {
	if x != nil {
		return x.ResourceProperties
	}
	return nil
}

type isGenerateAttributeBasedRecommendationsRequest_PriorityProfile interface {
	isGenerateAttributeBasedRecommendationsRequest_PriorityProfile()
}

type GenerateAttributeBasedRecommendationsRequest_RegularPriorityProfile struct {
	// Object of VMPriorityProfile for regular vms.
	RegularPriorityProfile *RegularPriorityProfile `protobuf:"bytes,3,opt,name=regular_priority_profile,json=regularPriorityProfile,proto3,oneof"`
}

type GenerateAttributeBasedRecommendationsRequest_SpotPriorityProfile struct {
	// Object of VMPriorityProfile for spot vms.
	SpotPriorityProfile *SpotPriorityProfile `protobuf:"bytes,4,opt,name=spot_priority_profile,json=spotPriorityProfile,proto3,oneof"`
}

func (*GenerateAttributeBasedRecommendationsRequest_RegularPriorityProfile) isGenerateAttributeBasedRecommendationsRequest_PriorityProfile() {
}

func (*GenerateAttributeBasedRecommendationsRequest_SpotPriorityProfile) isGenerateAttributeBasedRecommendationsRequest_PriorityProfile() {
}

// Response from generating attribute-based VM size recommendations
type GenerateAttributeBasedRecommendationsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RecommendedVmSizes *RecommendedVMSizes    `protobuf:"bytes,1,opt,name=recommended_vm_sizes,json=recommendedVmSizes,proto3" json:"recommended_vm_sizes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GenerateAttributeBasedRecommendationsResponse) Reset() {
	*x = GenerateAttributeBasedRecommendationsResponse{}
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAttributeBasedRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAttributeBasedRecommendationsResponse) ProtoMessage() {}

func (x *GenerateAttributeBasedRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAttributeBasedRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GenerateAttributeBasedRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateAttributeBasedRecommendationsResponse) GetRecommendedVmSizes() *RecommendedVMSizes {
	if x != nil {
		return x.RecommendedVmSizes
	}
	return nil
}

var File_apis_protos_azure_compute_v1_vmsizerecommender_proto protoreflect.FileDescriptor

const file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDesc = "" +
	"\n" +
	"4apis/protos/azure/compute/v1/vmsizerecommender.proto\x12\x10azure.compute.v1\"8\n" +
	"\fVMAttributes\x12(\n" +
	"\x10allowed_vm_sizes\x18\x01 \x03(\tR\x0eallowedVmSizes\"Y\n" +
	"\x12ResourceProperties\x12C\n" +
	"\rvm_attributes\x18\x01 \x01(\v2\x1e.azure.compute.v1.VMAttributesR\fvmAttributes\"\x93\x01\n" +
	"\x16RegularPriorityProfile\x12P\n" +
	"\x12capacity_unit_type\x18\x01 \x01(\x0e2\".azure.compute.v1.CapacityUnitTypeR\x10capacityUnitType\x12'\n" +
	"\x0ftarget_capacity\x18\x02 \x01(\rR\x0etargetCapacity\"\xb9\x01\n" +
	"\x13SpotPriorityProfile\x12P\n" +
	"\x12capacity_unit_type\x18\x01 \x01(\x0e2\".azure.compute.v1.CapacityUnitTypeR\x10capacityUnitType\x12'\n" +
	"\x10max_price_per_vm\x18\x02 \x01(\x02R\rmaxPricePerVm\x12'\n" +
	"\x0ftarget_capacity\x18\x03 \x01(\rR\x0etargetCapacity\"\xf2\x02\n" +
	"\x18RecommendationProperties\x12n\n" +
	"\x13restrictions_filter\x18\x01 \x01(\x0e2=.azure.compute.v1.RecommendationProperties.RestrictionsFilterR\x12restrictionsFilter\"\xe5\x01\n" +
	"\x12RestrictionsFilter\x12#\n" +
	"\x1fRESTRICTIONS_FILTER_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RESTRICTIONS_FILTER_NONE\x10\x01\x12*\n" +
	"&RESTRICTIONS_FILTER_OFFER_RESTRICTIONS\x10\x02\x12*\n" +
	"&RESTRICTIONS_FILTER_QUOTA_RESTRICTIONS\x10\x03\x124\n" +
	"0RESTRICTIONS_FILTER_QUOTA_AND_OFFER_RESTRICTIONS\x10\x04\"]\n" +
	"\x1bRecommendedVMSizeProperties\x12\x16\n" +
	"\x06family\x18\x01 \x01(\tR\x06family\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size\"\xc0\x01\n" +
	"\x12RecommendedVMSizes\x12W\n" +
	"\x10regular_vm_sizes\x18\x01 \x03(\v2-.azure.compute.v1.RecommendedVMSizePropertiesR\x0eregularVmSizes\x12Q\n" +
	"\rspot_vm_sizes\x18\x02 \x03(\v2-.azure.compute.v1.RecommendedVMSizePropertiesR\vspotVmSizes\"\x8a\x04\n" +
	",GenerateAttributeBasedRecommendationsRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12d\n" +
	"\x18regular_priority_profile\x18\x03 \x01(\v2(.azure.compute.v1.RegularPriorityProfileH\x00R\x16regularPriorityProfile\x12[\n" +
	"\x15spot_priority_profile\x18\x04 \x01(\v2%.azure.compute.v1.SpotPriorityProfileH\x00R\x13spotPriorityProfile\x12g\n" +
	"\x19recommendation_properties\x18\x05 \x01(\v2*.azure.compute.v1.RecommendationPropertiesR\x18recommendationProperties\x12U\n" +
	"\x13resource_properties\x18\x06 \x01(\v2$.azure.compute.v1.ResourcePropertiesR\x12resourcePropertiesB\x12\n" +
	"\x10priority_profile\"\x87\x01\n" +
	"-GenerateAttributeBasedRecommendationsResponse\x12V\n" +
	"\x14recommended_vm_sizes\x18\x01 \x01(\v2$.azure.compute.v1.RecommendedVMSizesR\x12recommendedVmSizes*`\n" +
	"\x10CapacityUnitType\x12\"\n" +
	"\x1eCAPACITY_UNIT_TYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$CAPACITY_UNIT_TYPE_VM_INSTANCE_COUNT\x10\x012\xd3\x01\n" +
	"&AttributeBasedVMSizeRecommenderService\x12\xa8\x01\n" +
	"%GenerateAttributeBasedRecommendations\x12>.azure.compute.v1.GenerateAttributeBasedRecommendationsRequest\x1a?.azure.compute.v1.GenerateAttributeBasedRecommendationsResponseB.Z,go.goms.io/fleet/pkg/protos/azure/compute/v1b\x06proto3"

var (
	file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescOnce sync.Once
	file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescData []byte
)

func file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescGZIP() []byte {
	file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescOnce.Do(func() {
		file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDesc), len(file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDesc)))
	})
	return file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDescData
}

var file_apis_protos_azure_compute_v1_vmsizerecommender_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_apis_protos_azure_compute_v1_vmsizerecommender_proto_goTypes = []any{
	(CapacityUnitType)(0),                                 // 0: azure.compute.v1.CapacityUnitType
	(RecommendationProperties_RestrictionsFilter)(0),      // 1: azure.compute.v1.RecommendationProperties.RestrictionsFilter
	(*VMAttributes)(nil),                                  // 2: azure.compute.v1.VMAttributes
	(*ResourceProperties)(nil),                            // 3: azure.compute.v1.ResourceProperties
	(*RegularPriorityProfile)(nil),                        // 4: azure.compute.v1.RegularPriorityProfile
	(*SpotPriorityProfile)(nil),                           // 5: azure.compute.v1.SpotPriorityProfile
	(*RecommendationProperties)(nil),                      // 6: azure.compute.v1.RecommendationProperties
	(*RecommendedVMSizeProperties)(nil),                   // 7: azure.compute.v1.RecommendedVMSizeProperties
	(*RecommendedVMSizes)(nil),                            // 8: azure.compute.v1.RecommendedVMSizes
	(*GenerateAttributeBasedRecommendationsRequest)(nil),  // 9: azure.compute.v1.GenerateAttributeBasedRecommendationsRequest
	(*GenerateAttributeBasedRecommendationsResponse)(nil), // 10: azure.compute.v1.GenerateAttributeBasedRecommendationsResponse
}
var file_apis_protos_azure_compute_v1_vmsizerecommender_proto_depIdxs = []int32{
	2,  // 0: azure.compute.v1.ResourceProperties.vm_attributes:type_name -> azure.compute.v1.VMAttributes
	0,  // 1: azure.compute.v1.RegularPriorityProfile.capacity_unit_type:type_name -> azure.compute.v1.CapacityUnitType
	0,  // 2: azure.compute.v1.SpotPriorityProfile.capacity_unit_type:type_name -> azure.compute.v1.CapacityUnitType
	1,  // 3: azure.compute.v1.RecommendationProperties.restrictions_filter:type_name -> azure.compute.v1.RecommendationProperties.RestrictionsFilter
	7,  // 4: azure.compute.v1.RecommendedVMSizes.regular_vm_sizes:type_name -> azure.compute.v1.RecommendedVMSizeProperties
	7,  // 5: azure.compute.v1.RecommendedVMSizes.spot_vm_sizes:type_name -> azure.compute.v1.RecommendedVMSizeProperties
	4,  // 6: azure.compute.v1.GenerateAttributeBasedRecommendationsRequest.regular_priority_profile:type_name -> azure.compute.v1.RegularPriorityProfile
	5,  // 7: azure.compute.v1.GenerateAttributeBasedRecommendationsRequest.spot_priority_profile:type_name -> azure.compute.v1.SpotPriorityProfile
	6,  // 8: azure.compute.v1.GenerateAttributeBasedRecommendationsRequest.recommendation_properties:type_name -> azure.compute.v1.RecommendationProperties
	3,  // 9: azure.compute.v1.GenerateAttributeBasedRecommendationsRequest.resource_properties:type_name -> azure.compute.v1.ResourceProperties
	8,  // 10: azure.compute.v1.GenerateAttributeBasedRecommendationsResponse.recommended_vm_sizes:type_name -> azure.compute.v1.RecommendedVMSizes
	9,  // 11: azure.compute.v1.AttributeBasedVMSizeRecommenderService.GenerateAttributeBasedRecommendations:input_type -> azure.compute.v1.GenerateAttributeBasedRecommendationsRequest
	10, // 12: azure.compute.v1.AttributeBasedVMSizeRecommenderService.GenerateAttributeBasedRecommendations:output_type -> azure.compute.v1.GenerateAttributeBasedRecommendationsResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_apis_protos_azure_compute_v1_vmsizerecommender_proto_init() }
func file_apis_protos_azure_compute_v1_vmsizerecommender_proto_init() {
	if File_apis_protos_azure_compute_v1_vmsizerecommender_proto != nil {
		return
	}
	file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes[7].OneofWrappers = []any{
		(*GenerateAttributeBasedRecommendationsRequest_RegularPriorityProfile)(nil),
		(*GenerateAttributeBasedRecommendationsRequest_SpotPriorityProfile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDesc), len(file_apis_protos_azure_compute_v1_vmsizerecommender_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_protos_azure_compute_v1_vmsizerecommender_proto_goTypes,
		DependencyIndexes: file_apis_protos_azure_compute_v1_vmsizerecommender_proto_depIdxs,
		EnumInfos:         file_apis_protos_azure_compute_v1_vmsizerecommender_proto_enumTypes,
		MessageInfos:      file_apis_protos_azure_compute_v1_vmsizerecommender_proto_msgTypes,
	}.Build()
	File_apis_protos_azure_compute_v1_vmsizerecommender_proto = out.File
	file_apis_protos_azure_compute_v1_vmsizerecommender_proto_goTypes = nil
	file_apis_protos_azure_compute_v1_vmsizerecommender_proto_depIdxs = nil
}
