{{- if .Values.azurePropertyChecker.isEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: property-config
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  config.json: {{ .Values.azurePropertyChecker.config | toJson | indent 4 | b64enc | quote }}
{{- end }}
